source "https://rubygems.org"
# Gemfile
ruby "3.2.4"

gem "rails", "~> 7.2.2"
gem "pg", "~> 1.5"
gem "puma", "~> 7.0"
gem "rack-cors"
gem "jbuilder"
gem "bootsnap", require: false
gem 'active_model_serializers', '~> 0.10.14'
gem 'rails-i18n', '~> 7.0', '>= 7.0.10'
gem 'devise-i18n', '~> 1.12'

group :development, :test do
  gem "rspec-rails"
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'shoulda-matchers', '~> 6.0'
  gem 'simplecov', require: false
  gem 'debug', '= 1.11.0', require: false
end

group :development do
  gem "rubocop", require: false
  gem "brakeman", require: false
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'erb', '~> 4.0'
  gem 'sqlite3', '~> 1.6'
end
gem 'dotenv-rails', groups: [:development, :test]
# 認証
gem "devise", "~> 4.9"
# トークン認証にする場合
gem "devise-jwt", "~> 0.12"

gem "image_processing", "~> 1.14"

gem "ruby-vips"        # vips を使う場合
